$script = <<-SCRIPT
mkdir /captain
SCRIPT


$random_password = ('a'..'z').to_a.shuffle[0,8].join

$CR_NUM_HOSTS = 1

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider "virtualbox" do |v|
    v.memory = 8092
    v.cpus = 2
  end
  
  cr_hosts = 1.step($CR_NUM_HOSTS,1).to_a
  cr_first_host = "http://www.192.168.60.20#{cr_hosts.first}.sslip.io:3000"

  config.vm.post_up_message = <<-CONFIG
  Caprover root user \"captain\" password is captain42. Visit the URL after five minutes or until Caprover has started successfully, which you can determine from docker logs on Vagrant virtual machine accessed via executing \"vagrant ssh\"`.
  #{cr_first_host}
  CONFIG
  
  cr_hosts.each do |h|
    idx = "#{h}"
    ip  = "192.168.60.20#{idx}"
    config.vm.define "cr#{idx}" do |cr_config|
    cr_config.vm.network "private_network", ip: ip
    cr_config.vm.provision "docker" do |d|
      d.post_install_provision "shell", inline: $script
      d.run "caprover/caprover-edge", args: "-e MAIN_NODE_IP_ADDRESS=#{ip} -e BY_PASS_PROXY_CHECK=TRUE -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain"
    end
  end  
end
end
