Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"

  config.vm.define "boxrover01", primary: true
  config.vm.define "boxrover02", primary: false 
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
  end
  config.vm.provision "docker" do |d|
    d.run "caprover/caprover", args: "-p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover"
  end
end
